find_channels:
  fields:
    query:
      required: true
      example: "ZDF"
      selector:
        text:
    limit:
      default: 30
      selector:
        number:
          min: 1
          max: 100
          mode: box
inspect_vod:
  fields:
    kind:
      required: true
      default: movie
      selector:
        select:
          options:
            - movie
            - episode
    id:
      required: true
      example: "123456"
      selector:
        text:
    extension:
      example: mkv
      selector:
        text:
find_vod:
  fields:
    query:
      required: true
      example: "matrix"
      selector:
        text:
    limit:
      default: 20
      selector:
        number:
          min: 1
          max: 50
          mode: box
