find_channels:
  fields:
    query:
      required: true
      example: "ZDF"
      selector:
        text:
    limit:
      default: 30
      selector:
        number:
          min: 1
          max: 100
          mode: box
